### PR TITLE
[Proposal] Adding Arcane Arteries.

### PR DESCRIPTION
**Pull request by TDarkShadow**
Arcane Blade: Utilizes the inherent magic of Thaumium to make your
dagger give you 500LP each time you prick yourself.

Elven Dagger: Utilizes metals granted to you by the Elves of Alfheim,
along with a little bit of mana, to grant you the ability to get 1000LP
(or 1 blank slate) each time you prick yourself.

Thaumic and Botanical replacements for Blood Runes: These give no buffs
to the Blood Altar, but can be used to help progress the tier of the
blood altar (e.g. A Blood altar with 3 Botanical, 3 Thaumic, and 2 Blood
Runes, below it will be Tier 2 - assuming they are placed correctly)

### CODE REVIEW

**Comment by nicogranelli** [comment]
I don't like this mod, it trivializes blood magic early game progression. 

It's like adding those mods that remove research or warp in thaumcraft. They are good options for people that just hate some mechanics of a particular mod, but I don't like it for the default pack.

Also a note: It kinda worked in regrowth because it was an attempt to simplify BM progression in the same way infinite coal do it for botania, and infinite shards do it for TC. But in this pack, with not super easy mob spawners, you actually have to work to progress in BM. And personally I like that

**Comment by TDarkShadow** [comment]
@nicogranelli Hmm, and how about using it as a more rewarding knife after going through Botania / Thaumcraft? Like using Void Metal / Terrasteel for the recipes.

**Comment by nicogranelli** [comment]
@TDarkShadow that's a very good idea.

**Comment by TDarkShadow** [comment]
@nicogranelli You can also make a custom knife / dagger with it and I would suggest making one with Witchery or Aura Cascade materials.

**Comment by DrasticDemise** [comment]
If you make the scripts and adjust the balance I may merge it, but it makes the core of the mod fairly arbitrarily by itself.

**Comment by BrizzleMFD** [comment]
Closing pull request, you can reopen it if modifications are made

**Pull request closed without merging**
